const config = {
  API_URL: process.env.REACT_APP_API_URL,
  RECAPTCHA_SITE_KEY: process.env.REACT_APP_GOOGLE_RECAPTCHA_SITE_KEY,
  STRIPE_P_KEY: process.env.REACT_APP_STRIPE_P_KEY,
  STRIPE_PRICE_ID: process.env.REACT_APP_STRIPE_PRO_PRICE,
  STRIPE_INDIA_PRICE_ID: process.env.REACT_APP_STRIPE_PRO_PRICE_INDIA,
};

export default config;
